# Generated by Django 4.2.4 on 2024-05-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bidder_name', models.CharField(max_length=50)),
                ('bidder_mobile', models.CharField(max_length=12, unique=True)),
                ('bidd_product', models.CharField(max_length=50)),
                ('bidd_price', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
