# Generated by Django 4.2.4 on 2024-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bidding_bidd_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bidder_mobile',
            field=models.CharField(max_length=12),
        ),
    ]
