# Generated by Django 4.2.4 on 2024-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_bidding_bidder_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bidd_product_ID',
            field=models.CharField(max_length=10),
        ),
    ]
