# Generated by Django 4.2.4 on 2024-05-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_bidding_bidder_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
