# Generated by Django 4.2.4 on 2024-05-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_cart_bidd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='product_icon',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
