# Generated by Django 4.2.4 on 2024-06-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_bidding_product_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='bidd_ID',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='mobile',
        ),
    ]
