# Generated by Django 4.2.4 on 2024-06-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_cart_address_remove_cart_bidd_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bidd_ID',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
