# Generated by Django 4.2.4 on 2024-06-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_cart_bidd_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
    ]
