# Generated by Django 4.2.4 on 2024-06-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_cart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='info',
        ),
    ]
